config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :admin_users
  devise_for :users
  namespace :admin do
    resources :terms
    resources :teams
    resources :games
    resources :cups
    resources :links
    root to: "terms#index"
  end
  get "index/index"
  resources :games
  resources :teams
  resources :terms
  resources :cups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#index"
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :cup
end

app/controllers/admin/terms_controller.rb
module Admin
  class TermsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: %i[ show edit update destroy ]

  # GET /terms or /terms.json
  def index
    @terms = Term.all
  end

  # GET /terms/1 or /terms/1.json
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
    @cups = Cup.all
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms or /terms.json
  def create
    @term = Term.new(term_params)

    respond_to do |format|
      if @term.save
        format.html { redirect_to term_url(@term), notice: "Term was successfully created." }
        format.json { render :show, status: :created, location: @term }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /terms/1 or /terms/1.json
  def update
    respond_to do |format|
      if @term.update(term_params)
        format.html { redirect_to term_url(@term), notice: "Term was successfully updated." }
        format.json { render :show, status: :ok, location: @term }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1 or /terms/1.json
  def destroy
    @term.destroy

    respond_to do |format|
      format.html { redirect_to terms_url, notice: "Term was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_term
    @term = Term.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def term_params
    params.require(:term).permit(:name, :cup_id)
  end
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/terms/_form.html.erb
<%= form_with(model: term) do |form| %>
  <% if term.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
        <% term.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cup_id, style: "display: block" %>
    <%= form.text_field :cup_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


<%= bootstrap_form_for(Term.new) do |f| %>
 <%= f.text_field :name %>
<% end %>

app/views/terms/_term.html.erb
<div id="<%= dom_id term %>">
  <p>
    <strong>Name:</strong>
    <%= term.name %>
  </p>

  <p>
    <strong>Cup:</strong>
    <%= term.cup_id %>
  </p>

</div>

app/views/terms/edit.html.erb
<h1>Editing term</h1>

<%= render "form", term: @term %>

<br>

<div>
  <%= link_to "Show this term", @term %> |
  <%= link_to "Back to terms", terms_path %>
</div>

app/views/terms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Terms</h1>

<div id="terms">
  <% @terms.each do |term| %>
    <%= render term %>
    <p>
      <%= link_to "Show this term", term %>
    </p>
  <% end %>
</div>

<%= link_to "New term", new_term_path %>

app/views/terms/new.html.erb
<h1>New term</h1>

<%= render "form", term: @term %>

<br>

<div>
  <%= link_to "Back to terms", terms_path %>
</div>

app/views/terms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @term %>

<div>
  <%= link_to "Edit this term", edit_term_path(@term) %> |
  <%= link_to "Back to terms", terms_path %>

  <%= button_to "Destroy this term", @term, method: :delete %>
</div>