config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :admin_users
  devise_for :users
  namespace :admin do
    resources :terms
    resources :teams
    resources :games
    resources :cups
    resources :links
    root to: "terms#index"
  end
  get "index/index"
  resources :games
  resources :teams
  resources :terms
  resources :cups
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "index#index"
end

app/models/cup.rb
class Cup < ApplicationRecord
end

app/controllers/admin/cups_controller.rb
module Admin
  class CupsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
  before_action :set_cup, only: %i[ show edit update destroy ]

  # GET /cups or /cups.json
  def index
    @cups = Cup.all
  end

  # GET /cups/1 or /cups/1.json
  def show
  end

  # GET /cups/new
  def new
    @cup = Cup.new
  end

  # GET /cups/1/edit
  def edit
  end

  # POST /cups or /cups.json
  def create
    @cup = Cup.new(cup_params)

    respond_to do |format|
      if @cup.save
        format.html { redirect_to cup_url(@cup), notice: "Cup was successfully created." }
        format.json { render :show, status: :created, location: @cup }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cups/1 or /cups/1.json
  def update
    respond_to do |format|
      if @cup.update(cup_params)
        format.html { redirect_to cup_url(@cup), notice: "Cup was successfully updated." }
        format.json { render :show, status: :ok, location: @cup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cups/1 or /cups/1.json
  def destroy
    @cup.destroy

    respond_to do |format|
      format.html { redirect_to cups_url, notice: "Cup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cup
      @cup = Cup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cup_params
      params.require(:cup).permit(:name)
    end
end

app/helpers/cups_helper.rb
module CupsHelper
end

app/views/cups/_cup.html.erb
<div id="<%= dom_id cup %>">
  <p>
    <strong>Name:</strong>
    <%= cup.name %>
  </p>

</div>

app/views/cups/_form.html.erb
<%= form_with(model: cup) do |form| %>
  <% if cup.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cup.errors.count, "error") %> prohibited this cup from being saved:</h2>

      <ul>
        <% cup.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cups/edit.html.erb
<h1>Editing cup</h1>

<%= render "form", cup: @cup %>

<br>

<div>
  <%= link_to "Add term", new_term_path %>
  <%= link_to "Show this cup", @cup %> |
  <%= link_to "Back to cups", cups_path %>
</div>

app/views/cups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cups</h1>

<div id="cups">
  <% @cups.each do |cup| %>
    <%= render cup %>
    <p>
      <%= link_to "Show this cup", cup %>
    </p>
  <% end %>
</div>

<%= link_to "New cup", new_cup_path %>

app/views/cups/new.html.erb
<h1>New cup</h1>

<%= render "form", cup: @cup %>

<br>

<div>
  <%= link_to "Back to cups", cups_path %>
</div>

app/views/cups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cup %>

<div>
  <%= link_to "Edit this cup", edit_cup_path(@cup) %> |
  <%= link_to "Back to cups", cups_path %>

  <%= button_to "Destroy this cup", @cup, method: :delete %>
</div>